config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :title, presence: true,
                    length: { minimum: 5 }
  has_attached_file :avatar, styles: { large: "500x500>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to @recipe
    else
      render 'new'
    end
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render 'edit'
    end
  end

  def new
    @recipe = Recipe.new
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    redirect_to recipes_path
  end

  private

    def recipe_params
      params.require(:recipe).permit(:title, :directions, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/home/index.html.erb
<div class="container">
  <div class="banner">
    <div class="right">Last Updated: 10/21/2016</div>
    <h1>Welcome to RecipeBox.io</h1>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
    <ul id="slide-out" class="side-nav fixed">
      <li class="bold"><%= link_to "Home", root_path %></li>
      <li class="bold"><a href="#!">Appetizers</a></li>
      <li class="bold"><a href="#!">Poultry</a></li>
      <li class="bold"><a href="#!">Seafood</a></li>
      <li class="bold"><a href="#!">Meat</a></li>
      <li class="bold"><a href="#!">Baking</a></li>
      <li class="bold"><a href="#!">Dessert</a></li>
     </ul>
     <a href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a>

     <%= link_to new_recipe_path do %>
       <div class="stage">
         <div class="cube">
           <figure class="back"></figure>
           <figure class="left"></figure>
           <figure class="right"></figure>
           <figure class="front"></figure>
           <figure class="divider"></figure>
           <figure class="label"><div style="padding-left:3px">Baking</div></figure>
           <figure class="card">
             <div style="padding-right:3px; text-align:right;">
               Almond Cookies
               <div class="red-line-separator"></div>
               <div class="blue-line-separator"></div>
               <div class="blue-line-separator"></div>
               <div class="blue-line-separator"></div>
             </div>
           </figure>
           <figure class="card2">
             <div style="padding-right:3px; text-align:right;">
               Banana Bread
               <div class="red-line-separator"></div>
               <div class="blue-line-separator"></div>
               <div class="blue-line-separator"></div>
               <div class="blue-line-separator"></div>
             </div>
           </figure>
           <figure class="card3">
             <div style="padding-right:3px; text-align:right;">
               Cupcakes
               <div class="red-line-separator"></div>
               <div class="blue-line-separator"></div>
               <div class="blue-line-separator"></div>
               <div class="blue-line-separator"></div>
             </div>
           </figure>
           <figure class="divider2"></figure>
           <figure class="label2"><div style="padding-left:3px">Entrees</div></figure>
           <figure class="card4">
             <div style="padding-right:3px; text-align:right;">
               Salmon
               <div class="red-line-separator"></div>
               <div class="blue-line-separator"></div>
               <div class="blue-line-separator"></div>
               <div class="blue-line-separator"></div>
             </div>
           </figure>
           <figure class="card5">
             <div style="padding-right:3px; text-align:right;">
               Filet Mignon
               <div class="red-line-separator"></div>
               <div class="blue-line-separator"></div>
               <div class="blue-line-separator"></div>
               <div class="blue-line-separator"></div>
             </div>
           </figure>
           <figure class="card6">
             <div style="padding-right:3px; text-align:right;">
               Pasta
               <div class="red-line-separator"></div>
               <div class="blue-line-separator"></div>
               <div class="blue-line-separator"></div>
               <div class="blue-line-separator"></div>
             </div>
           </figure>
           <figure class="divider3"></figure>
           <figure class="label3"><div style="padding-left:3px">Apps</div></figure>
           <figure class="card7">
             <div style="padding-right:3px; text-align:right;">
               Grill
               <div class="red-line-separator"></div>
               <div class="blue-line-separator"></div>
               <div class="blue-line-separator"></div>
               <div class="blue-line-separator"></div>
             </div>
           </figure>
         </div>
       </div>
       <div class="post-it">Recipe Box</figure>
     <% end %>
   </header>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
<% if @recipe.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@recipe.errors.count, "error") %>
      prohibited this article from being saved:
    </h2>
    <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :directions %><br>
  <%= f.text_area :directions %>
</p>

<p>
  <%= f.label :avatar %><br>
  <%= f.file_field :avatar %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form' %>

<% link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Listing Recipes</h1>
<%= link_to 'New recipe', new_recipe_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Directions</th>
    <th colspan="2"></th>
  </tr>

  <% @recipes.each do |recipe| %>
    <tr>
      <td><%= recipe.title %></td>
      <td><%= recipe.directions %></td>
      <td><%= image_tag recipe.avatar.url(:thumb) %></td>
      <td><%= link_to 'Show', recipe_path(recipe) %></td>
      <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
      <td><%= link_to 'Destroy', recipe_path(recipe),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @recipe.title %>
</p>

<p>
  <strong>Directions:</strong>
  <%= @recipe.directions %>
</p>
  <strong>Photo:</strong>
  <%= image_tag @recipe.avatar(:large) %>
</p>
<p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>